sudo: required
language: node_js
node_js:
  - stable
services:
  - docker
addons:
  ssh_known_hosts: "${SSH_HOST}"
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - npm install -g gatsby-cli
  - npm install
script:
  - gatsby build
  - cd public
  - cp index.html 404.html
  - cd ..
  - docker-compose -f docker-compose.yml build
  - docker tag noted $DOCKERHUB_NOTED
  - docker push $DOCKERHUB_NOTED
after_script:
  #- rm -rf .git
  - eval "$(ssh-agent -s)" && ssh-add ~/.ssh/travis_rsa && ssh -o "StrictHostKeyChecking=no" ${REMOTE_USER}@${SSH_HOST} -v exit
  - git remote add deploy "${REMOTE_USER}@${SSH_HOST}:/opt/note" && git config user.name "Travis CI" && git config user.email "kiwsan+travis@gmail.com" && git status && git add docker-compose.yml && git commit -m "deploy"
  - git push --force deploy master
before_install:
  - openssl aes-256-cbc -K $encrypted_58ca57a8e487_key -iv $encrypted_58ca57a8e487_iv
    -in travis_rsa.enc -out travis_rsa -d
