version: '3'

services:

  gatsby-site:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: gatsby-site
    image: noted
    restart: unless-stopped
    ports:
      - 8000:80
